version: '2'
services:
    21points-app:
        image: 21points
        external_links:
            - 21points-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/21points
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    21points-postgresql:
        extends:
            file: postgresql.yml
            service: 21points-postgresql
